name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - requests=2.28.1
  - pip=20.3.3
  - mlflow=1.14.1
  - hydra-core=1.2.0
  - pip:
      - wandb==0.13.2
      - hydra-joblib-launcher==1.2.0
